///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace xpath
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("294a3a8d-4680-412c-8761-bb6fc5a11307", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the xpathRepository repository.
        /// </summary>
        public static xpathRepository repo = xpathRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
            CancelValue = "";
            CancelledValue = "";
            selectitem = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

        string _CancelValue;

        /// <summary>
        /// Gets or sets the value of variable CancelValue.
        /// </summary>
        [TestVariable("a3ec175c-272a-49e0-a085-999978bf6020")]
        public string CancelValue
        {
            get { return _CancelValue; }
            set { _CancelValue = value; }
        }

        string _CancelledValue;

        /// <summary>
        /// Gets or sets the value of variable CancelledValue.
        /// </summary>
        [TestVariable("acd7dffe-f07a-4674-93b5-1de83f6c9659")]
        public string CancelledValue
        {
            get { return _CancelledValue; }
            set { _CancelledValue = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable selectitem.
        /// </summary>
        [TestVariable("4046c290-c6cc-4aa9-8b8d-ac2375b3148a")]
        public string selectitem
        {
            get { return repo.selectitem; }
            set { repo.selectitem = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'XPathDemos.CancelValue' and assigning its value to variable 'CancelValue'.", repo.XPathDemos.CancelValueInfo, new RecordItemIndex(0));
            CancelValue = repo.XPathDemos.CancelValue.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'XPathDemos.CancellingValue' and assigning its value to variable 'CancelledValue'.", repo.XPathDemos.CancellingValueInfo, new RecordItemIndex(1));
            CancelledValue = repo.XPathDemos.CancellingValue.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", CancelValue, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "User", CancelledValue, new RecordItemIndex(3));
            
            CompareValues(CancelValue, CancelledValue);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
