///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace xpath
{
    public partial class Recording1
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CompareValues(string CancelValue, string CancelledValue)
        {
        	int cancelvalueint = int.Parse(CancelValue.Remove(0,1));
        	int cancelledvalueint = int.Parse(CancelledValue);
        	
        	if(cancelvalueint+cancelledvalueint==0){
        		Ranorex.Report.Info("It worked");
        	} else
        	{
        		Ranorex.Report.Failure("Values are different");
        	}
        }

    }
}
