///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace xpath
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the xpathRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("d88ed6f1-ee19-405b-8c9c-e364703c0ccb")]
    public partial class xpathRepository : RepoGenBaseFolder
    {
        static xpathRepository instance = new xpathRepository();
        xpathRepositoryFolders.XPathDemosAppFolder _xpathdemos;

        /// <summary>
        /// Gets the singleton class instance representing the xpathRepository element repository.
        /// </summary>
        [RepositoryFolder("d88ed6f1-ee19-405b-8c9c-e364703c0ccb")]
        public static xpathRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public xpathRepository() 
            : base("xpathRepository", "/", null, 0, false, "d88ed6f1-ee19-405b-8c9c-e364703c0ccb", ".\\RepositoryImages\\xpathRepositoryd88ed6f1.rximgres")
        {
            _xpathdemos = new xpathRepositoryFolders.XPathDemosAppFolder(this);
        }

#region Variables

        string _selectitem = "1";

        /// <summary>
        /// Gets or sets the value of variable selectitem.
        /// </summary>
        [TestVariable("4046c290-c6cc-4aa9-8b8d-ac2375b3148a")]
        public string selectitem
        {
            get { return _selectitem; }
            set { _selectitem = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d88ed6f1-ee19-405b-8c9c-e364703c0ccb")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The XPathDemos folder.
        /// </summary>
        [RepositoryFolder("ce7fe618-6757-4f2b-8d2a-ff584bd0285c")]
        public virtual xpathRepositoryFolders.XPathDemosAppFolder XPathDemos
        {
            get { return _xpathdemos; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class xpathRepositoryFolders
    {
        /// <summary>
        /// The XPathDemosAppFolder folder.
        /// </summary>
        [RepositoryFolder("ce7fe618-6757-4f2b-8d2a-ff584bd0285c")]
        public partial class XPathDemosAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cancelvalueInfo;
            RepoItemInfo _cancellingvalueInfo;

            /// <summary>
            /// Creates a new XPathDemos  folder.
            /// </summary>
            public XPathDemosAppFolder(RepoGenBaseFolder parentFolder) :
                    base("XPathDemos", "/dom[@caption='XPath Demos']", parentFolder, 30000, null, false, "ce7fe618-6757-4f2b-8d2a-ff584bd0285c", "")
            {
                _cancelvalueInfo = new RepoItemInfo(this, "CancelValue", ".//table//td[@innertext='Canceled']/preceding-sibling::td[2][$selectitem]", 30000, null, "43932dd5-cf9b-4342-ab50-15b41aebeae4");
                _cancellingvalueInfo = new RepoItemInfo(this, "CancellingValue", ".//table//td[@innertext='Canceled']/../following-sibling::tr/td[@innertext='Cancelling']/../td[2][$selectitem]", 30000, null, "eceea30f-89d3-49b0-86f0-25b069641a63");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ce7fe618-6757-4f2b-8d2a-ff584bd0285c")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ce7fe618-6757-4f2b-8d2a-ff584bd0285c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CancelValue item.
            /// </summary>
            [RepositoryItem("43932dd5-cf9b-4342-ab50-15b41aebeae4")]
            public virtual Ranorex.TdTag CancelValue
            {
                get
                {
                    return _cancelvalueInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The CancelValue item info.
            /// </summary>
            [RepositoryItemInfo("43932dd5-cf9b-4342-ab50-15b41aebeae4")]
            public virtual RepoItemInfo CancelValueInfo
            {
                get
                {
                    return _cancelvalueInfo;
                }
            }

            /// <summary>
            /// The CancellingValue item.
            /// </summary>
            [RepositoryItem("eceea30f-89d3-49b0-86f0-25b069641a63")]
            public virtual Ranorex.TdTag CancellingValue
            {
                get
                {
                    return _cancellingvalueInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The CancellingValue item info.
            /// </summary>
            [RepositoryItemInfo("eceea30f-89d3-49b0-86f0-25b069641a63")]
            public virtual RepoItemInfo CancellingValueInfo
            {
                get
                {
                    return _cancellingvalueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}